// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "title": "Outfit Backend API",
        "version": "1.0",
        "contact": {}
    },
    "basePath": "/api",
    "paths": {
        "/healthz": {"get": {"summary": "Liveness check"}},
        "/readyz": {"get": {"summary": "Readiness check"}},
        "/auth/register": {"post": {"summary": "Register user"}},
        "/auth/login": {"post": {"summary": "Login user"}},
        "/auth/refresh": {"post": {"summary": "Refresh token"}},
        "/auth/logout": {"post": {"summary": "Logout user", "security": [{"BearerAuth": []}]}},
        "/auth/profile": {"get": {"summary": "Current profile", "security": [{"BearerAuth": []}]}},
        "/products": {"get": {"summary": "List products"}},
        "/products/{id}": {"get": {"summary": "Get product by ID"}},
        "/categories": {"get": {"summary": "List categories"}},
        "/categories/tree": {"get": {"summary": "Category tree"}},
        "/cart": {"get": {"summary": "Get user cart", "security": [{"BearerAuth": []}]}},
        "/cart/items": {"post": {"summary": "Add cart item", "security": [{"BearerAuth": []}]}},
        "/orders": {"get": {"summary": "List my orders", "security": [{"BearerAuth": []}]}, "post": {"summary": "Create order", "security": [{"BearerAuth": []}]}},
        "/orders/my": {"get": {"summary": "List my orders (compat)", "security": [{"BearerAuth": []}]}},
        "/orders/{id}": {"get": {"summary": "Get order by ID", "security": [{"BearerAuth": []}]}}
    },
    "securityDefinitions": {
        "BearerAuth": {"type": "apiKey", "name": "Authorization", "in": "header"}
    }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Outfit Backend API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
